Sprint 1
boorav4ik/middle.messenger.praktikum.yandex pull request #1
Opened 2022-11-15 22:37 UTC by boorav4ik

2022-11-16 16:12 UTC, podlovchenko requested changes
Привет, в целом все хорошо, но определение стилей через теги не очень хорошая практика, в теории 1 спринта есть урок по архитектуре css дизайн языка, там описаны возможные проблемы
Так же оставила еще несколько замечаний в коде

2022-11-16 16:12 UTC, podlovchenko commented on package.json
> +    "handlebars": "^4.7.7"
В devDependencies указывается то, что необходимо для сборки и разработки приложения, в dependencies то, что необходимо непосредственно для работу приложения (express)

2022-11-16 16:12 UTC, podlovchenko commented on package.json
> +    "@anikin/parcel-transformer-handlebars": "^1.0.9",
Лучше задавать фиксированные версии зависимостям. Если однажды решишь, удалить package-lock.json файл и попытаться повторно установить зависимости с помощью команды npm install, npm установит последние версии зависимостей, что может привести к ошибкам

2022-11-16 16:12 UTC, podlovchenko commented on .gitignore
> +/package-lock.json
Лучше оставить package-lock.json в репозитории, таким образом будет гарантироваться, что локально и на ci установятся одинаковые версии зависимостей

2022-11-16 16:12 UTC, podlovchenko commented on server.js
> +const PORT = 3000;
Часто требуется возможность получить порт снаружи скрипта, не изменяя код, это можно сделать через переменное окружение:
process.env.PORT || PORT;
https://nodejs.org/dist/latest-v8.x/docs/api/process.html

2022-11-16 16:12 UTC, podlovchenko commented on src/css/chats.css
> +aside>header>input[type="search"] {
Такую завязанность на иерархии сложно поддерживать и вносить изменения, лучше использовать классы

2022-11-16 21:29 UTC, boorav4ik commented on package.json
> +    "handlebars": "^4.7.7"
Перенёс handlebars в devDependencies

2022-11-16 21:30 UTC, boorav4ik commented on package.json
> +    "@anikin/parcel-transformer-handlebars": "^1.0.9",
Задал фиксированные значения версий

2022-11-16 21:31 UTC, boorav4ik commented on .gitignore
> +/package-lock.json
Удалил package-lock из .gitignore

2022-11-16 21:32 UTC, boorav4ik commented on server.js
> +const PORT = 3000;
прописал PORT=3000 в process.env

2022-11-18 13:21 UTC, podlovchenko approved these changes
Работу принимаю, но все-таки лучше совсем избегать зависимости от иерархии тегов в определении стилей)

2022-11-26 05:24 UTC, merged